/*
 * JS for Fast_API generated by Appery.io
 */
Apperyio.getProjectGUID = function() {
    return 'c040e2a6-a83c-43f6-a4cf-595310b6031d';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}
Apperyio.AppPages = [{
    "name": "Fast_API",
    "location": "Fast_API.html"
}, {
    "name": "Info",
    "location": "Info.html"
}, {
    "name": "Welkom",
    "location": "Welkom.html"
}];

function Fast_API_js() {
    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilelabel_10': 'Fast_API_mobilelabel_10',
        'mobilelabel_9': 'Fast_API_mobilelabel_9',
        'Error': 'Fast_API_Error',
        'loading_gif': 'Fast_API_loading_gif',
        'mobilecarousel_4': 'Fast_API_mobilecarousel_4',
        'mobilecarouselitem_5': 'Fast_API_mobilecarouselitem_5',
        'html_8': 'Fast_API_html_8',
        'mobilecarouselitem_6': 'Fast_API_mobilecarouselitem_6',
        'mobilecarouselitem_7': 'Fast_API_mobilecarouselitem_7',
        'mobilebutton_2': 'Fast_API_mobilebutton_2',
        'mobilebutton_11': 'Fast_API_mobilebutton_11'
    };
    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }
    /*
     * Nonvisual components
     */
    Apperyio.mappings = Apperyio.mappings || {};
    Apperyio.mappings["Fast_API_mobilebarcode3_onsuccess_mapping_0"] = {
        "homeScreen": "Fast_API",
        "directions": [
            {
                "from_name": "mobilebarcode3",
                "from_type": "SERVICE_RESPONSE",
                "to_name": "barcode_try",
                "to_type": "SESSION_STORAGE",
                "mappings": [
                    {
                        "source": "$['data']['text']",
                        "target": "$"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["Fast_API_mobilebarcode3_onbeforesend_mapping_0"] = {
        "homeScreen": "Fast_API",
        "directions": [
            {
                "from_name": "tru",
                "from_type": "SESSION_STORAGE",
                "to_name": "Fast_API",
                "to_type": "UI",
                "mappings": [
                    {
                        "source": "$",
                        "target": "$['loading_gif:visible']"
                    }
                ]
            },
            {
                "from_name": "fals",
                "from_type": "SESSION_STORAGE",
                "to_name": "Fast_API",
                "to_type": "UI",
                "mappings": [
                    {
                        "source": "$",
                        "target": "$['Error:visible']"
                    },
                    {
                        "source": "$",
                        "target": "$['mobilecarousel_4:visible']"
                    },
                    {
                        "source": "$",
                        "target": "$['html_8:visible']"
                    },
                    {
                        "source": "$",
                        "target": "$['mobilelabel_9:visible']"
                    },
                    {
                        "source": "$",
                        "target": "$['mobilelabel_10:visible']"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["Fast_API_mobilebarcode3_oncomplete_mapping_1"] = {
        "homeScreen": "Fast_API",
        "directions": [
            {
                "from_name": "tru",
                "from_type": "SESSION_STORAGE",
                "to_name": "Fast_API",
                "to_type": "UI",
                "mappings": [
                    {
                        "source": "$",
                        "target": "$['loading_gif:visible']"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["Fast_API_mobilebarcode3_onerror_mapping_0"] = {
        "homeScreen": "Fast_API",
        "directions": [
            {
                "from_name": "tru",
                "from_type": "SESSION_STORAGE",
                "to_name": "Fast_API",
                "to_type": "UI",
                "mappings": [
                    {
                        "source": "$",
                        "target": "$['Error:visible']"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["Fast_API_restservice1_onsuccess_mapping_0"] = {
        "homeScreen": "Fast_API",
        "directions": [
            {
                "from_name": "restservice1",
                "from_type": "SERVICE_RESPONSE",
                "to_name": "Fast_API",
                "to_type": "UI",
                "mappings": [
                    {
                        "source": "$['body']['name']",
                        "target": "$['mobilelabel_10:text']"
                    },
                    {
                        "source": "$['body']['ecoscore']",
                        "target": "$['mobilelabel_9:text']"
                    },
                    {
                        "source": "$['body']['eco_img']",
                        "target": "$['html_8:rawHtml']"
                    },
                    {
                        "source": "$['body']['features']",
                        "target": "$['mobilecarouselitem_6:dataTitle']"
                    },
                    {
                        "source": "$['body']['nutrients']",
                        "target": "$['mobilecarouselitem_7:dataTitle']"
                    },
                    {
                        "source": "$['body']['visibility']",
                        "target": "$['mobilelabel_9:visible']"
                    },
                    {
                        "source": "$['body']['visibility']",
                        "target": "$['mobilecarousel_4:visible']"
                    },
                    {
                        "source": "$['body']['visibility']",
                        "target": "$['html_8:visible']"
                    }
                ]
            },
            {
                "from_name": "tru",
                "from_type": "SESSION_STORAGE",
                "to_name": "Fast_API",
                "to_type": "UI",
                "mappings": [
                    {
                        "source": "$",
                        "target": "$['mobilelabel_10:visible']"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["Fast_API_restservice1_onbeforesend_mapping_0"] = {
        "homeScreen": "Fast_API",
        "directions": [
            {
                "from_name": "barcode_try",
                "from_type": "SESSION_STORAGE",
                "to_name": "restservice1",
                "to_type": "SERVICE_REQUEST",
                "to_default": {
                    "headers": {},
                    "parameters": {},
                    "body": null
                },
                "mappings": [
                    {
                        "source": "$",
                        "target": "$['parameters']['barcode']"
                    }
                ]
            },
            {
                "from_name": "tru",
                "from_type": "SESSION_STORAGE",
                "to_name": "Fast_API",
                "to_type": "UI",
                "mappings": [
                    {
                        "source": "$",
                        "target": "$['loading_gif:visible']"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["Fast_API_restservice1_oncomplete_mapping_0"] = {
        "homeScreen": "Fast_API",
        "directions": [
            {
                "from_name": "fals",
                "from_type": "SESSION_STORAGE",
                "to_name": "Fast_API",
                "to_type": "UI",
                "mappings": [
                    {
                        "source": "$",
                        "target": "$['loading_gif:visible']"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["Fast_API_restservice1_onerror_mapping_0"] = {
        "homeScreen": "Fast_API",
        "directions": [
            {
                "from_name": "tru",
                "from_type": "SESSION_STORAGE",
                "to_name": "Fast_API",
                "to_type": "UI",
                "mappings": [
                    {
                        "source": "$",
                        "target": "$['Error:visible']"
                    }
                ]
            }
        ]
    };
    Apperyio.datasources = Apperyio.datasources || {};
    window.mobilebarcode3 = Apperyio.datasources.mobilebarcode3 = new Apperyio.DataSource(BarcodeService, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["Fast_API_mobilebarcode3_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {
            try {
                restservice1.execute({});
            } catch (e) {
                console.error(e);
                hideSpinner();
            };
            Apperyio.processMappingAction(Apperyio.mappings["Fast_API_mobilebarcode3_oncomplete_mapping_1"]);
        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["Fast_API_mobilebarcode3_onsuccess_mapping_0"]);
        },
        "onError": function(jqXHR, textStatus, errorThrown) {
            Apperyio.processMappingAction(Apperyio.mappings["Fast_API_mobilebarcode3_onerror_mapping_0"]);
        }
    });
    window.restservice1 = Apperyio.datasources.restservice1 = new Apperyio.DataSource(PHP_API, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["Fast_API_restservice1_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {
            Apperyio.processMappingAction(Apperyio.mappings["Fast_API_restservice1_oncomplete_mapping_0"]);
        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["Fast_API_restservice1_onsuccess_mapping_0"]);
        },
        "onError": function(jqXHR, textStatus, errorThrown) {
            Apperyio.processMappingAction(Apperyio.mappings["Fast_API_restservice1_onerror_mapping_0"]);
        }
    });
    Apperyio.CurrentScreen = 'Fast_API';
    _.chain(Apperyio.mappings)
        .filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        })
        .each(Apperyio.UIHandler.hideTemplateComponents);
    /*
     * Events and handlers
     */
    // On Load
    var Fast_API_onLoad = function() {
        Fast_API_elementsExtraJS();
        Fast_API_deviceEvents();
        Fast_API_windowEvents();
        Fast_API_elementsEvents();
    };
    // screen window events
    function Fast_API_windowEvents() {
        $('#Fast_API').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });
    };
    // device events
    function Fast_API_deviceEvents() {
        document.addEventListener("deviceready", function() {
        });
    };
    // screen elements extra js
    function Fast_API_elementsExtraJS() {
        // screen (Fast_API) extra code
        /* mobilecarousel_4*/
        var mobilecarousel_4_options = {
            indicatorsListClass: "ui-carousel-indicators",
            showIndicator: true,
            showTitle: true,
            titleBuildIn: false,
            titleIsText: true,
            animationDuration: 250,
            useLegacyAnimation: false,
            enabled: true,
        }
        Apperyio.__registerComponent('mobilecarousel_4', new Apperyio.ApperyMobileCarouselComponent("Fast_API_mobilecarousel_4", mobilecarousel_4_options));
        $("#Fast_API_mobilecarouselitem_5").attr("reRender", "mobilecarousel_4");
        $("#Fast_API_mobilecarouselitem_6").attr("reRender", "mobilecarousel_4");
        $("#Fast_API_mobilecarouselitem_7").attr("reRender", "mobilecarousel_4");
    };
    // screen elements handler
    function Fast_API_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });
        $(document).off("click", '#Fast_API_footer [name="mobilebutton_2"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    try {
                        mobilebarcode3.execute({});
                    } catch (e) {
                        console.error(e);
                        hideSpinner();
                    };
                }
            },
        }, '#Fast_API_footer [name="mobilebutton_2"]');
        $(document).off("click", '#Fast_API_footer [name="mobilebutton_11"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('Info', {
                        reverse: false
                    });
                }
            },
        }, '#Fast_API_footer [name="mobilebutton_11"]');
    };
    $(document).off("pagebeforeshow", "#Fast_API").on("pagebeforeshow", "#Fast_API", function(event, ui) {
        Apperyio.CurrentScreen = "Fast_API";
        _.chain(Apperyio.mappings)
            .filter(function(m) {
                return m.homeScreen === Apperyio.CurrentScreen;
            })
            .each(Apperyio.UIHandler.hideTemplateComponents);
    });
    Fast_API_onLoad();
};
$(document).off("pagecreate", "#Fast_API").on("pagecreate", "#Fast_API", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    Fast_API_js();
});