/*
 * JS for Info generated by Appery.io
 */
Apperyio.getProjectGUID = function() {
    return 'c040e2a6-a83c-43f6-a4cf-595310b6031d';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}
Apperyio.AppPages = [{
    "name": "Fast_API",
    "location": "Fast_API.html"
}, {
    "name": "Info",
    "location": "Info.html"
}, {
    "name": "Welkom",
    "location": "Welkom.html"
}];

function Info_js() {
    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilebutton_7': 'Info_mobilebutton_7',
        'html_2': 'Info_html_2',
        'mobilelabel_9': 'Info_mobilelabel_9',
        'mobilelabel_11': 'Info_mobilelabel_11',
        'mobilelabel_10': 'Info_mobilelabel_10',
        'mobilelabel_12': 'Info_mobilelabel_12',
        'mobilelabel_13': 'Info_mobilelabel_13',
        'mobilelabel_14': 'Info_mobilelabel_14',
        'mobilelabel_15': 'Info_mobilelabel_15',
        'mobilelabel_16': 'Info_mobilelabel_16',
        'mobilelabel_17': 'Info_mobilelabel_17',
        'mobilelabel_19': 'Info_mobilelabel_19',
        'mobilelabel_18': 'Info_mobilelabel_18'
    };
    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }
    /*
     * Nonvisual components
     */
    Apperyio.mappings = Apperyio.mappings || {};
    Apperyio.mappings["Info_mobilebarcode2_onsuccess_mapping_0"] = {
        "homeScreen": "Info",
        "directions": [
            {
                "from_name": "mobilebarcode2",
                "from_type": "SERVICE_RESPONSE",
                "to_name": "barcode_try",
                "to_type": "SESSION_STORAGE",
                "mappings": [
                    {
                        "source": "$['data']['text']",
                        "target": "$"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["Info_mobilebarcode2_onbeforesend_mapping_0"] = {
        "homeScreen": "Info",
        "directions": []
    };
    Apperyio.datasources = Apperyio.datasources || {};
    window.mobilebarcode2 = Apperyio.datasources.mobilebarcode2 = new Apperyio.DataSource(BarcodeService, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["Info_mobilebarcode2_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {
        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["Info_mobilebarcode2_onsuccess_mapping_0"]);
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });
    Apperyio.CurrentScreen = 'Info';
    _.chain(Apperyio.mappings)
        .filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        })
        .each(Apperyio.UIHandler.hideTemplateComponents);
    /*
     * Events and handlers
     */
    // On Load
    var Info_onLoad = function() {
        Info_elementsExtraJS();
        Info_deviceEvents();
        Info_windowEvents();
        Info_elementsEvents();
    };
    // screen window events
    function Info_windowEvents() {
        $('#Info').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });
    };
    // device events
    function Info_deviceEvents() {
        document.addEventListener("deviceready", function() {
        });
    };
    // screen elements extra js
    function Info_elementsExtraJS() {
        // screen (Info) extra code
    };
    // screen elements handler
    function Info_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });
        $(document).off("click", '#Info_mobileheader [name="mobilebutton_7"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('Fast_API', {
                        reverse: false
                    });
                }
            },
        }, '#Info_mobileheader [name="mobilebutton_7"]');
    };
    $(document).off("pagebeforeshow", "#Info").on("pagebeforeshow", "#Info", function(event, ui) {
        Apperyio.CurrentScreen = "Info";
        _.chain(Apperyio.mappings)
            .filter(function(m) {
                return m.homeScreen === Apperyio.CurrentScreen;
            })
            .each(Apperyio.UIHandler.hideTemplateComponents);
    });
    Info_onLoad();
};
$(document).off("pagecreate", "#Info").on("pagecreate", "#Info", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    Info_js();
});