/*
 * JS for Scan generated by Appery.io
 */
Apperyio.getProjectGUID = function() {
    return 'c28eddf6-d470-46eb-8abb-03d1d315da5d';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}
Apperyio.AppPages = [{
    "name": "Scan",
    "location": "Scan.html"
}, {
    "name": "Screen1",
    "location": "Screen1.html"
}];

function Scan_js() {
    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'barcode': 'Scan_barcode',
        'name': 'Scan_name',
        'quantity': 'Scan_quantity',
        'mobilebutton_2': 'Scan_mobilebutton_2'
    };
    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }
    /*
     * Nonvisual components
     */
    Apperyio.mappings = Apperyio.mappings || {};
    Apperyio.mappings["Scan_mobilebutton_2_onclick_mapping_1"] = {
        "homeScreen": "Scan",
        "directions": [
            {
                "from_name": "productBarcode",
                "from_type": "LOCAL_STORAGE",
                "to_name": "Scan",
                "to_type": "UI",
                "mappings": [
                    {
                        "source": "$",
                        "target": "$['quantity:text']"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["Scan_mobilebarcode1_onsuccess_mapping_0"] = {
        "homeScreen": "Scan",
        "directions": [
            {
                "from_name": "mobilebarcode1",
                "from_type": "SERVICE_RESPONSE",
                "to_name": "productBarcode",
                "to_type": "LOCAL_STORAGE",
                "mappings": [
                    {
                        "source": "$['data']['text']",
                        "target": "$"
                    }
                ]
            },
            {
                "from_name": "mobilebarcode1",
                "from_type": "SERVICE_RESPONSE",
                "to_name": "Scan",
                "to_type": "UI",
                "mappings": [
                    {
                        "source": "$['data']['text']",
                        "target": "$['barcode:text']"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["Scan_mobilebarcode1_onbeforesend_mapping_0"] = {
        "homeScreen": "Scan",
        "directions": []
    };
    Apperyio.mappings["Scan_restservice1_onsuccess_mapping_0"] = {
        "homeScreen": "Scan",
        "directions": [
            {
                "from_name": "restservice1",
                "from_type": "SERVICE_RESPONSE",
                "to_name": "Scan",
                "to_type": "UI",
                "mappings": [
                    {
                        "source": "$['body']['name']",
                        "target": "$['name:text']"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["Scan_restservice1_onbeforesend_mapping_0"] = {
        "homeScreen": "Scan",
        "directions": [
            {
                "from_name": "productBarcode",
                "from_type": "LOCAL_STORAGE",
                "to_name": "restservice1",
                "to_type": "SERVICE_REQUEST",
                "to_default": {
                    "headers": {},
                    "parameters": {},
                    "body": null
                },
                "mappings": [
                    {
                        "source": "$",
                        "target": "$['headers']['barcode']"
                    },
                    {
                        "source": "$",
                        "target": "$['parameters']['barcode']"
                    }
                ]
            }
        ]
    };
    Apperyio.datasources = Apperyio.datasources || {};
    window.mobilebarcode1 = Apperyio.datasources.mobilebarcode1 = new Apperyio.DataSource(BarcodeService, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["Scan_mobilebarcode1_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {
        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["Scan_mobilebarcode1_onsuccess_mapping_0"]);
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });
    window.restservice1 = Apperyio.datasources.restservice1 = new Apperyio.DataSource(StampyAPI, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["Scan_restservice1_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {
        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["Scan_restservice1_onsuccess_mapping_0"]);
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });
    Apperyio.CurrentScreen = 'Scan';
    _.chain(Apperyio.mappings)
        .filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        })
        .each(Apperyio.UIHandler.hideTemplateComponents);
    /*
     * Events and handlers
     */
    // On Load
    var Scan_onLoad = function() {
        Scan_elementsExtraJS();
        Scan_deviceEvents();
        Scan_windowEvents();
        Scan_elementsEvents();
    };
    // screen window events
    function Scan_windowEvents() {
        $('#Scan').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });
    };
    // device events
    function Scan_deviceEvents() {
        document.addEventListener("deviceready", function() {
        });
    };
    // screen elements extra js
    function Scan_elementsExtraJS() {
        // screen (Scan) extra code
    };
    // screen elements handler
    function Scan_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });
        $(document).off("click", '#Scan_mobilecontainer [name="mobilebutton_2"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    try {
                        mobilebarcode1.execute({});
                    } catch (e) {
                        console.error(e);
                        hideSpinner();
                    };
                    Apperyio.processMappingAction(Apperyio.mappings["Scan_mobilebutton_2_onclick_mapping_1"]);
                    try {
                        restservice1.execute({});
                    } catch (e) {
                        console.error(e);
                        hideSpinner();
                    };
                }
            },
        }, '#Scan_mobilecontainer [name="mobilebutton_2"]');
    };
    $(document).off("pagebeforeshow", "#Scan").on("pagebeforeshow", "#Scan", function(event, ui) {
        Apperyio.CurrentScreen = "Scan";
        _.chain(Apperyio.mappings)
            .filter(function(m) {
                return m.homeScreen === Apperyio.CurrentScreen;
            })
            .each(Apperyio.UIHandler.hideTemplateComponents);
    });
    Scan_onLoad();
};
$(document).off("pagecreate", "#Scan").on("pagecreate", "#Scan", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    Scan_js();
});