/*
 * JS for Welkom generated by Appery.io
 */
Apperyio.getProjectGUID = function() {
    return 'c040e2a6-a83c-43f6-a4cf-595310b6031d';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}
Apperyio.AppPages = [{
    "name": "Fast_API",
    "location": "Fast_API.html"
}, {
    "name": "Info",
    "location": "Info.html"
}, {
    "name": "Welkom",
    "location": "Welkom.html"
}];

function Welkom_js() {
    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobileimage_2': 'Welkom_mobileimage_2',
        'mobilebutton_3': 'Welkom_mobilebutton_3'
    };
    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }
    /*
     * Nonvisual components
     */
    Apperyio.mappings = Apperyio.mappings || {};
    Apperyio.mappings["Welkom_BOOL_onsuccess_mapping_0"] = {
        "homeScreen": "Welkom",
        "directions": [
            {
                "from_name": "BOOL",
                "from_type": "SERVICE_RESPONSE",
                "to_name": "tru",
                "to_type": "SESSION_STORAGE",
                "mappings": [
                    {
                        "source": "$['body']['true']",
                        "target": "$"
                    }
                ]
            },
            {
                "from_name": "BOOL",
                "from_type": "SERVICE_RESPONSE",
                "to_name": "fals",
                "to_type": "SESSION_STORAGE",
                "mappings": [
                    {
                        "source": "$['body']['false']",
                        "target": "$"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["Welkom_BOOL_onbeforesend_mapping_0"] = {
        "homeScreen": "Welkom",
        "directions": []
    };
    Apperyio.datasources = Apperyio.datasources || {};
    window.BOOL = Apperyio.datasources.BOOL = new Apperyio.DataSource(BOOL_API, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["Welkom_BOOL_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {
        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["Welkom_BOOL_onsuccess_mapping_0"]);
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });
    Apperyio.CurrentScreen = 'Welkom';
    _.chain(Apperyio.mappings)
        .filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        })
        .each(Apperyio.UIHandler.hideTemplateComponents);
    /*
     * Events and handlers
     */
    // On Load
    var Welkom_onLoad = function() {
        Welkom_elementsExtraJS();
        try {
            BOOL.execute({});
        } catch (e) {
            console.error(e);
            hideSpinner();
        };
        Welkom_deviceEvents();
        Welkom_windowEvents();
        Welkom_elementsEvents();
    };
    // screen window events
    function Welkom_windowEvents() {
        $('#Welkom').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });
    };
    // device events
    function Welkom_deviceEvents() {
        document.addEventListener("deviceready", function() {
        });
    };
    // screen elements extra js
    function Welkom_elementsExtraJS() {
        // screen (Welkom) extra code
    };
    // screen elements handler
    function Welkom_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });
        $(document).off("click", '#Welkom_mobilecontainer [name="mobilebutton_3"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('Fast_API', {
                        reverse: false
                    });
                }
            },
        }, '#Welkom_mobilecontainer [name="mobilebutton_3"]');
    };
    $(document).off("pagebeforeshow", "#Welkom").on("pagebeforeshow", "#Welkom", function(event, ui) {
        Apperyio.CurrentScreen = "Welkom";
        _.chain(Apperyio.mappings)
            .filter(function(m) {
                return m.homeScreen === Apperyio.CurrentScreen;
            })
            .each(Apperyio.UIHandler.hideTemplateComponents);
    });
    Welkom_onLoad();
};
$(document).off("pagecreate", "#Welkom").on("pagecreate", "#Welkom", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    Welkom_js();
});